project:
  title: "Research Template"
  output-dir: _products
  execute-dir: project
  pre-render: 
    - utils/check_packages.R      # install required packages
    - utils/remove_artifacts.ts   # remove previously constructed files
  render:
    # if analysis is split into multiple docs, add them here
    - analysis/organize_data.qmd
    - analysis/analysis.qmd
    - paper/
    - presentation/
    - "!bibliography/"
