---
title: "Organize Data Notebook"
---

```{r}
#label: timestamp-start

timestamp()
```

```{r}
#| label: setup
#| include: false
library(here)
source(here("utils","check_packages.R"))
source(here("utils","functions.R"))
```

This quarto doc is used to organize the data.

# Download Data

```{r}
#| label: download-data

# This script is for use when the data will be downloaded from an external
# source like Google Drive to each collaborator's local machine. This script
# checks if the data version on the remote repo matches the local and if not
# it downloads the required data and then updates the local version. If you are 
# not using external data, then this code chunk can be removed.

# get latest data version from repo
repo_version <- read_yaml(here("data", "data_raw", "data_version.yml"))$version

# get local data version
local_version <- NULL
local_version_path <- here("data", "data_raw", "data_version_local.yml")
if (file_exists(local_version_path)) {
  local_version <- read_yaml(local_version_path)$version
} else {
  local_version <- "none"
}

if(local_version != repo_version) {
  
  # TODO: add code here to download the data locally, e.g. from Google Drive
  # with the googledrive R package.
  
}

# update local to repo version
write_yaml(list(version = repo_version), 
           here("data", "data_raw", "data_version_local.yml"))
```


```{r}
#label: timestamp-end

timestamp()
```